# Generated by Django 4.2.7 on 2023-11-21 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameverse', '0003_remove_cartitem_product_cartitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='item_price',
        ),
    ]
